### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Ntwali-Josue** [xJokeer/Awesome_books#6]
** @xJokeer @rotimiazeez  Great work on implementing all the required features 💯 , though there are few things that you can work on ✍🏾 👨🏾‍💻 :**

- Please try to change the background of your books list, so that the content of your book can be read and seen clearly.
![image](https://user-images.githubusercontent.com/58233753/129214818-9a289d53-81b3-4846-a22c-78ffeb393096.png)

- Please try to fix the button size, for it to not change when the content size increases or decreases.
![image](https://user-images.githubusercontent.com/58233753/129215074-96c28bc7-e61d-4675-812f-b8fa7d299770.png)

**Comment by CarlosE-Feliz** [comment]
Thx u bro! i'll work on that!
